"""Init1

Revision ID: 4bbf1dccaada
Revises: 2f6d548f4f9b
Create Date: 2023-12-20 01:29:55.533628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbf1dccaada'
down_revision: Union[str, None] = '2f6d548f4f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_type', sa.Column('sequence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_type', 'sequence')
    # ### end Alembic commands ###
